-- ==========================================================================
-- Supabase Database Schema for Ward 5 Beawar Campaign Website
-- Copy and paste this entire script into your Supabase SQL Editor and click RUN
-- ==========================================================================

-- 1. Create Supporters (समर्थक) Table
create table if not exists ward5_supporters (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  area text default 'वार्ड नं. 5'
);

-- 2. Create Grievances / Problems (जन-समस्या) Table
create table if not exists ward5_grievances (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  phone text not null,
  area text not null,
  problem_type text not null,
  detail text not null,
  status text default 'लंबित (Pending)'
);

-- 3. Enable Row Level Security (RLS)
alter table ward5_supporters enable row level security;
alter table ward5_grievances enable row level security;

-- 4. Create Public Access Policies (Allow anonymous submissions from voters)
create policy "Public insert supporters" on ward5_supporters for insert with check (true);
create policy "Public select supporters" on ward5_supporters for select using (true);

create policy "Public insert grievances" on ward5_grievances for insert with check (true);
create policy "Public select grievances" on ward5_grievances for select using (true);

-- Done! Your database is ready to receive submissions in real-time.
